// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoapEM5k8MpIkYx4XaXHick5JLhHac2X8',
    appId: '1:1044296974145:web:6cda86f83652b87c6a6bc0',
    messagingSenderId: '1044296974145',
    projectId: 'easyrepair-12',
    authDomain: 'easyrepair-12.firebaseapp.com',
    storageBucket: 'easyrepair-12.firebasestorage.app',
    measurementId: 'G-VG3628263W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlse5JuMQ9PFLWQViFCgnrTcAsRvUcCPc',
    appId: '1:1044296974145:android:39eebc22f2eb6d246a6bc0',
    messagingSenderId: '1044296974145',
    projectId: 'easyrepair-12',
    storageBucket: 'easyrepair-12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2chCLmk6qHtcx0FxepkIV2Ux0RXijhvY',
    appId: '1:1044296974145:ios:352ea81e1db964a26a6bc0',
    messagingSenderId: '1044296974145',
    projectId: 'easyrepair-12',
    storageBucket: 'easyrepair-12.firebasestorage.app',
    iosBundleId: 'com.example.easyrepairApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2chCLmk6qHtcx0FxepkIV2Ux0RXijhvY',
    appId: '1:1044296974145:ios:352ea81e1db964a26a6bc0',
    messagingSenderId: '1044296974145',
    projectId: 'easyrepair-12',
    storageBucket: 'easyrepair-12.firebasestorage.app',
    iosBundleId: 'com.example.easyrepairApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoapEM5k8MpIkYx4XaXHick5JLhHac2X8',
    appId: '1:1044296974145:web:35131364bda635c36a6bc0',
    messagingSenderId: '1044296974145',
    projectId: 'easyrepair-12',
    authDomain: 'easyrepair-12.firebaseapp.com',
    storageBucket: 'easyrepair-12.firebasestorage.app',
    measurementId: 'G-SGPK7BRPMM',
  );
}
