import { Type } from 'class-transformer';
import {
  ArrayMaxSize,
  ArrayMinSize,
  IsArray,
  IsBoolean,
  IsIn,
  IsISO8601,
  IsNotEmpty,
  IsOptional,
  IsString,
  MaxLength,
  ValidateNested,
} from 'class-validator';
import {
  AGREEMENT_LOCALES,
  TRADE_CODES,
  USTAAD_DOCUMENT_TYPES,
} from '../../agreements/source/agreement-source.types';

/**
 * Evidence that ONE of the three documents was actually opened and accepted.
 *
 * Everything here describes what the Ustaad saw — never who they are. Identity,
 * timestamps, hashes and the acceptance id are all resolved server-side; a
 * value sent here for any of those would simply be ignored.
 */
export class AgreementEvidenceDto {
  @IsString()
  @IsIn(USTAAD_DOCUMENT_TYPES as unknown as string[], {
    message: 'documentType must be one of the three Ustaad agreements',
  })
  documentType!: string;

  @IsString()
  @IsNotEmpty()
  @MaxLength(40)
  version!: string;

  /** SHA-256 of the source text the viewer rendered. */
  @IsString()
  @IsNotEmpty()
  @MaxLength(128)
  sourceHash!: string;

  @IsString()
  @IsIn(AGREEMENT_LOCALES as unknown as string[])
  agreementLocale!: string;

  /** Only the trade document carries one; null on the other two. */
  @IsOptional()
  @IsString()
  @IsIn(TRADE_CODES as unknown as string[])
  applicableTrade?: string | null;

  /** When the viewer finished loading this exact document. */
  @IsISO8601()
  viewedAt!: string;

  @IsBoolean()
  checkboxAccepted!: boolean;
}

/**
 * Body of POST /workers/profile-completion/submit.
 *
 * Exactly three evidence objects — one per Ustaad document. The Customer
 * document is not an accepted value for documentType, so it cannot be smuggled
 * in, and neither more nor fewer than three entries are accepted.
 */
export class SubmitProfileCompletionDto {
  /**
   * One id per submission attempt, generated by the app. A retry or a
   * double-tapped Submit reuses it, so the same three immutable records come
   * back instead of a second set being created.
   */
  @IsString()
  @IsNotEmpty()
  @MaxLength(100)
  submissionAttemptId!: string;

  @IsArray()
  @ArrayMinSize(USTAAD_DOCUMENT_TYPES.length, {
    message: 'All three agreements must be accepted',
  })
  @ArrayMaxSize(USTAAD_DOCUMENT_TYPES.length, {
    message: 'Exactly three agreement acceptances are expected',
  })
  @ValidateNested({ each: true })
  @Type(() => AgreementEvidenceDto)
  agreements!: AgreementEvidenceDto[];
}
